# Generated by Django 3.2.12 on 2024-07-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerimages',
            name='footer',
        ),
        migrations.AddField(
            model_name='footerimages',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
