# Generated by Django 3.2.12 on 2024-07-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0003_footer_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='sub_title',
            new_name='sub_title1',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='title',
            new_name='title1',
        ),
        migrations.AddField(
            model_name='banner',
            name='sub_title2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='sub_title3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='title3',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='title4',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='title5',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
