# Generated by Django 3.2.12 on 2024-07-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0004_auto_20240724_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default=1, upload_to='images/category/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footerimages',
            name='img',
            field=models.ImageField(upload_to='images/footer/'),
        ),
        migrations.AlterField(
            model_name='navbartop',
            name='info_icon_img',
            field=models.ImageField(upload_to='images/icon/'),
        ),
        migrations.AlterField(
            model_name='navbartop',
            name='logo_img',
            field=models.ImageField(upload_to='images/logo/'),
        ),
    ]
