# Generated by Django 3.2.12 on 2024-07-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0006_auto_20240726_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productenter',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
